from decimal import Decimal

mock_jobs = [
    {
        "title": "Fix Leaking Kitchen Sink",
        "description": "Kitchen sink has been leaking under the cabinet for two days.",
        "budget_min": Decimal("75.00"),
        "budget_max": Decimal("200.00"),
        "display_location": "New York, NY",
        "latitude": Decimal("40.7128"),
        "longitude": Decimal("-74.0060"),
    },
    {
        "title": "Paint Living Room",
        "description": "Need two coats of light gray paint applied to the living room walls.",
        "budget_min": Decimal("300.00"),
        "budget_max": Decimal("700.00"),
        "display_location": "Brooklyn, NY",
        "latitude": Decimal("40.6782"),
        "longitude": Decimal("-73.9442"),
    },
    {
        "title": "Replace Bathroom Tiles",
        "description": "Old bathroom floor tiles need to be removed and replaced.",
        "budget_min": Decimal("500.00"),
        "budget_max": Decimal("1200.00"),
        "display_location": "Queens, NY",
        "latitude": Decimal("40.7282"),
        "longitude": Decimal("-73.7949"),
    },
    {
        "title": "Install Ceiling Fan",
        "description": "Install a new ceiling fan in the master bedroom.",
        "budget_min": Decimal("100.00"),
        "budget_max": Decimal("300.00"),
        "display_location": "Bronx, NY",
        "latitude": Decimal("40.8448"),
        "longitude": Decimal("-73.8648"),
    },
    {
        "title": "Repair Roof Leak",
        "description": "Small roof leak causing water stains after heavy rain.",
        "budget_min": Decimal("600.00"),
        "budget_max": Decimal("1800.00"),
        "display_location": "Staten Island, NY",
        "latitude": Decimal("40.5795"),
        "longitude": Decimal("-74.1502"),
    },
    {
        "title": "Install Hardwood Flooring",
        "description": "Replace carpet with hardwood flooring in two bedrooms.",
        "budget_min": Decimal("1500.00"),
        "budget_max": Decimal("3500.00"),
        "display_location": "Jersey City, NJ",
        "latitude": Decimal("40.7178"),
        "longitude": Decimal("-74.0431"),
    },
    {
        "title": "Electrical Panel Upgrade",
        "description": "Upgrade electrical panel from 100A to 200A service.",
        "budget_min": Decimal("1800.00"),
        "budget_max": Decimal("4000.00"),
        "display_location": "Hoboken, NJ",
        "latitude": Decimal("40.7439"),
        "longitude": Decimal("-74.0324"),
    },
    {
        "title": "Fence Installation",
        "description": "Install a 6-foot wooden privacy fence around the backyard.",
        "budget_min": Decimal("1200.00"),
        "budget_max": Decimal("2800.00"),
        "display_location": "Newark, NJ",
        "latitude": Decimal("40.7357"),
        "longitude": Decimal("-74.1724"),
    },
    {
        "title": "HVAC Maintenance",
        "description": "Annual inspection and servicing of central HVAC system.",
        "budget_min": Decimal("150.00"),
        "budget_max": Decimal("450.00"),
        "display_location": "Yonkers, NY",
        "latitude": Decimal("40.9312"),
        "longitude": Decimal("-73.8988"),
    },
    {
        "title": "Deck Repair",
        "description": "Replace damaged deck boards and reinforce railing.",
        "budget_min": Decimal("700.00"),
        "budget_max": Decimal("1800.00"),
        "display_location": "White Plains, NY",
        "latitude": Decimal("41.0330"),
        "longitude": Decimal("-73.7629"),
    },
    {
        "title": "Garage Door Replacement",
        "description": "Replace old garage door with an insulated automatic model.",
        "budget_min": Decimal("900.00"),
        "budget_max": Decimal("2200.00"),
        "display_location": "Long Island, NY",
        "latitude": Decimal("40.7891"),
        "longitude": Decimal("-73.1350"),
    },
    {
        "title": "Window Replacement",
        "description": "Replace six drafty windows with energy-efficient models.",
        "budget_min": Decimal("2500.00"),
        "budget_max": Decimal("6000.00"),
        "display_location": "Buffalo, NY",
        "latitude": Decimal("42.8864"),
        "longitude": Decimal("-78.8784"),
    },
    {
        "title": "Fix Leaking Kitchen Sink",
        "description": "Kitchen sink has been leaking under the cabinet for two days.",
        "budget_min": Decimal("75.00"),
        "budget_max": Decimal("200.00"),
        "display_location": "New York, NY",
        "latitude": Decimal("40.7128"),
        "longitude": Decimal("-74.0060"),
    },
    {
        "title": "Paint Living Room",
        "description": "Need two coats of light gray paint applied to the living room walls.",
        "budget_min": Decimal("300.00"),
        "budget_max": Decimal("700.00"),
        "display_location": "Brooklyn, NY",
        "latitude": Decimal("40.6782"),
        "longitude": Decimal("-73.9442"),
    },
    {
        "title": "Replace Bathroom Tiles",
        "description": "Old bathroom floor tiles need to be removed and replaced.",
        "budget_min": Decimal("500.00"),
        "budget_max": Decimal("1200.00"),
        "display_location": "Queens, NY",
        "latitude": Decimal("40.7282"),
        "longitude": Decimal("-73.7949"),
    },
    {
        "title": "Install Ceiling Fan",
        "description": "Install a new ceiling fan in the master bedroom.",
        "budget_min": Decimal("100.00"),
        "budget_max": Decimal("300.00"),
        "display_location": "Bronx, NY",
        "latitude": Decimal("40.8448"),
        "longitude": Decimal("-73.8648"),
    },
    {
        "title": "Repair Roof Leak",
        "description": "Small roof leak causing water stains after heavy rain.",
        "budget_min": Decimal("600.00"),
        "budget_max": Decimal("1800.00"),
        "display_location": "Staten Island, NY",
        "latitude": Decimal("40.5795"),
        "longitude": Decimal("-74.1502"),
    },
    {
        "title": "Install Hardwood Flooring",
        "description": "Replace carpet with hardwood flooring in two bedrooms.",
        "budget_min": Decimal("1500.00"),
        "budget_max": Decimal("3500.00"),
        "display_location": "Jersey City, NJ",
        "latitude": Decimal("40.7178"),
        "longitude": Decimal("-74.0431"),
    },
    {
        "title": "Electrical Panel Upgrade",
        "description": "Upgrade electrical panel from 100A to 200A service.",
        "budget_min": Decimal("1800.00"),
        "budget_max": Decimal("4000.00"),
        "display_location": "Hoboken, NJ",
        "latitude": Decimal("40.7439"),
        "longitude": Decimal("-74.0324"),
    },
    {
        "title": "Fence Installation",
        "description": "Install a 6-foot wooden privacy fence around the backyard.",
        "budget_min": Decimal("1200.00"),
        "budget_max": Decimal("2800.00"),
        "display_location": "Newark, NJ",
        "latitude": Decimal("40.7357"),
        "longitude": Decimal("-74.1724"),
    },
    {
        "title": "HVAC Maintenance",
        "description": "Annual inspection and servicing of central HVAC system.",
        "budget_min": Decimal("150.00"),
        "budget_max": Decimal("450.00"),
        "display_location": "Yonkers, NY",
        "latitude": Decimal("40.9312"),
        "longitude": Decimal("-73.8988"),
    },
    {
        "title": "Deck Repair",
        "description": "Replace damaged deck boards and reinforce railing.",
        "budget_min": Decimal("700.00"),
        "budget_max": Decimal("1800.00"),
        "display_location": "White Plains, NY",
        "latitude": Decimal("41.0330"),
        "longitude": Decimal("-73.7629"),
    },
    {
        "title": "Garage Door Replacement",
        "description": "Replace old garage door with an insulated automatic model.",
        "budget_min": Decimal("900.00"),
        "budget_max": Decimal("2200.00"),
        "display_location": "Long Island, NY",
        "latitude": Decimal("40.7891"),
        "longitude": Decimal("-73.1350"),
    },
    {
        "title": "Window Replacement",
        "description": "Replace six drafty windows with energy-efficient models.",
        "budget_min": Decimal("2500.00"),
        "budget_max": Decimal("6000.00"),
        "display_location": "Buffalo, NY",
        "latitude": Decimal("42.8864"),
        "longitude": Decimal("-78.8784"),
    },
    {
        "title": "Fix Leaking Kitchen Sink",
        "description": "Kitchen sink has been leaking under the cabinet for two days.",
        "budget_min": Decimal("75.00"),
        "budget_max": Decimal("200.00"),
        "display_location": "New York, NY",
        "latitude": Decimal("40.7128"),
        "longitude": Decimal("-74.0060"),
    },
    {
        "title": "Paint Living Room",
        "description": "Need two coats of light gray paint applied to the living room walls.",
        "budget_min": Decimal("300.00"),
        "budget_max": Decimal("700.00"),
        "display_location": "Brooklyn, NY",
        "latitude": Decimal("40.6782"),
        "longitude": Decimal("-73.9442"),
    },
    {
        "title": "Replace Bathroom Tiles",
        "description": "Old bathroom floor tiles need to be removed and replaced.",
        "budget_min": Decimal("500.00"),
        "budget_max": Decimal("1200.00"),
        "display_location": "Queens, NY",
        "latitude": Decimal("40.7282"),
        "longitude": Decimal("-73.7949"),
    },
    {
        "title": "Install Ceiling Fan",
        "description": "Install a new ceiling fan in the master bedroom.",
        "budget_min": Decimal("100.00"),
        "budget_max": Decimal("300.00"),
        "display_location": "Bronx, NY",
        "latitude": Decimal("40.8448"),
        "longitude": Decimal("-73.8648"),
    },
    {
        "title": "Repair Roof Leak",
        "description": "Small roof leak causing water stains after heavy rain.",
        "budget_min": Decimal("600.00"),
        "budget_max": Decimal("1800.00"),
        "display_location": "Staten Island, NY",
        "latitude": Decimal("40.5795"),
        "longitude": Decimal("-74.1502"),
    },
    {
        "title": "Install Hardwood Flooring",
        "description": "Replace carpet with hardwood flooring in two bedrooms.",
        "budget_min": Decimal("1500.00"),
        "budget_max": Decimal("3500.00"),
        "display_location": "Jersey City, NJ",
        "latitude": Decimal("40.7178"),
        "longitude": Decimal("-74.0431"),
    },
    {
        "title": "Electrical Panel Upgrade",
        "description": "Upgrade electrical panel from 100A to 200A service.",
        "budget_min": Decimal("1800.00"),
        "budget_max": Decimal("4000.00"),
        "display_location": "Hoboken, NJ",
        "latitude": Decimal("40.7439"),
        "longitude": Decimal("-74.0324"),
    },
    {
        "title": "Fence Installation",
        "description": "Install a 6-foot wooden privacy fence around the backyard.",
        "budget_min": Decimal("1200.00"),
        "budget_max": Decimal("2800.00"),
        "display_location": "Newark, NJ",
        "latitude": Decimal("40.7357"),
        "longitude": Decimal("-74.1724"),
    },
    {
        "title": "HVAC Maintenance",
        "description": "Annual inspection and servicing of central HVAC system.",
        "budget_min": Decimal("150.00"),
        "budget_max": Decimal("450.00"),
        "display_location": "Yonkers, NY",
        "latitude": Decimal("40.9312"),
        "longitude": Decimal("-73.8988"),
    },
    {
        "title": "Deck Repair",
        "description": "Replace damaged deck boards and reinforce railing.",
        "budget_min": Decimal("700.00"),
        "budget_max": Decimal("1800.00"),
        "display_location": "White Plains, NY",
        "latitude": Decimal("41.0330"),
        "longitude": Decimal("-73.7629"),
    },
    {
        "title": "Garage Door Replacement",
        "description": "Replace old garage door with an insulated automatic model.",
        "budget_min": Decimal("900.00"),
        "budget_max": Decimal("2200.00"),
        "display_location": "Long Island, NY",
        "latitude": Decimal("40.7891"),
        "longitude": Decimal("-73.1350"),
    },
    {
        "title": "Window Replacement",
        "description": "Replace six drafty windows with energy-efficient models.",
        "budget_min": Decimal("2500.00"),
        "budget_max": Decimal("6000.00"),
        "display_location": "Buffalo, NY",
        "latitude": Decimal("42.8864"),
        "longitude": Decimal("-78.8784"),
    }
]
