"""add is_deleted and deleted_at fields in the File model

Revision ID: 62df2f1deca5
Revises: c75090f51ddc
Create Date: 2025-10-28 16:57:15.158288+00:00

"""
from collections.abc import Sequence
from typing import Union

# revision identifiers, used by Alembic.
revision: str = '62df2f1deca5'
down_revision: Union[str, None] = 'c75090f51ddc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
