"""add file fields

Revision ID: 1d840e5fdac2
Revises: 6befb92e081b
Create Date: 2025-10-21 16:39:30.729184+00:00

"""
from collections.abc import Sequence
from typing import Union

# revision identifiers, used by Alembic.
revision: str = '1d840e5fdac2'
down_revision: Union[str, None] = '6befb92e081b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
