### register worker
POST http://localhost:8000/api/v1/auth/register
Content-Type: application/json

{
"name": "john doe",
"username" : "johndoe",
"email": "test@test.com",
"password": "1A123456",
"role_type": "worker"
}

### login worker with wrong password or wrong username
POST http://localhost:8000/api/v1/auth/login
Content-Type: application/json

{
  "username_or_email" : "wrong_username",
  "password": "123456"
}

### login worker and capture token
POST http://localhost:8000/api/v1/auth/login
Content-Type: application/json

{
  "username_or_email": "test@test.com",
  "password": "1A123456"
}

> {% client.global.set("access_token", response.body.access_token) %}

### fetch worker profile — uses token from login
GET http://localhost:8000/api/v1/user/me
Authorization: Bearer {{access_token}}


### fetch users
GET http://localhost:8000/api/v1/users

### register customer
POST http://localhost:8000/api/v1/auth/register
Content-Type: application/json

{
  "name": "customer name",
  "username": "custusername",
  "email": "cust@test.com",
  "password": "Secure123",
  "role_type": "customer"
}

### login customer
POST http://localhost:8000/api/v1/auth/login
Content-Type: application/json

{
  "username_or_email": "cust@test.com",
  "password": "Secure123"
}